# Site settings
title: Wales
client:
  name: Visit Wales
  link: http://www.visitwales.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Start your next Wales adventure here. Zip-line along vast quarries, visit remote islands, gaze at a sea of stars – your adventure awaits, laid out on these pages to inspire your Welsh getaway. Discover epic, cross-country routes and little-known hideaways, adrenaline-fuelled activities and inspired natural sights. Find your luxury hotel, enter our incredible competition, and craft your very own adventure in Wales.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/wales" # the subpath of your site, e.g. /blog/
img:     "/wales/_assets/img"
css:     "/wales/_assets/css"
js:      "/wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed